name: Executing Shell Script with Actions
on: [push]
jobs:
  executing-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: chmod +x ../script.sh
      - run: sh ../script.sh
        shell: bash

